name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'renkunx/reference'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install
      - run: npm run build
      - run: cp -rp icons ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
